"""Initial migration

Revision ID: b4fbf5bc2fd1
Revises: 
Create Date: 2025-03-13 17:46:59.688871

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b4fbf5bc2fd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('member_id', sa.INTEGER(), server_default=sa.text("nextval('members_member_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('member_id', name='members_pkey'),
    sa.UniqueConstraint('email', name='members_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('books',
    sa.Column('book_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_borrowed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('borrowed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('borrowed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['borrowed_by'], ['members.member_id'], name='books_borrowed_by_fkey'),
    sa.PrimaryKeyConstraint('book_id', name='books_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('members')
    # ### end Alembic commands ###
