"""Create members and books tables

Revision ID: c377659cee6e
Revises: 
Create Date: 2025-03-17 21:57:14.881437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c377659cee6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_pkey', 'books', type_='primary')
    
    # Alter the 'id' column to be auto-incrementing
    op.alter_column(
        'books',
        'id',
        existing_type=sa.Integer(),
        autoincrement=True,
        nullable=False
    )

    # Re-add the primary key constraint on the 'id' column
    op.create_primary_key('books_pkey', 'books', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='members_pkey'),
    sa.UniqueConstraint('email', name='members_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_borrowed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('borrowed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('borrowed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['borrowed_by'], ['members.id'], name='books_borrowed_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='books_pkey')
    )
    # ### end Alembic commands ###
